Add `type` to script tag
ocsigen/tyxml pull request #273
Opened 2020-07-21 13:35 UTC by ulrikstrid

2021-01-21 17:22 UTC, Drup requested changes
Oh no, I just realized that I had a review on suspend that I never pushed? Sorry about that.

I don't like the convention so much, We should pick more consistent names.

2021-04-22 09:24 UTC, Drup commented
@ulrikstrid I'm planing a release soon, do I have time to make the changes to get that in ?

2021-04-22 10:05 UTC, ulrikstrid commented
As discussed "offline", I'll try to get to it within a week.

2021-04-27 18:22 UTC, ulrikstrid commented on lib/html_types.mli
> +    | `Async | `Charset | `Src | `Defer | `Mime_type | `Type
Do I understand correctly that I should remove my new variant and change `` `Mime_type `` to `` `Script_type? ``

2021-11-29 21:23 UTC, cemerick commented
Looks like this has gone stale; if the patch is okay otherwise, I could try to rebase, etc.?

2021-11-30 06:01 UTC, ulrikstrid commented
Feel free to take this @cemerick

2021-12-01 18:34 UTC, closed without merging